// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutCursorTrail from "@/components/sections/about/AboutCursorTrail";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
              <AboutCursorTrail
        textAnimation="fade-blur"
        tag="Explore Our Club"
        title="What are you looking for?"
        media={[{"imageSrc":"https://storage.googleapis.com/webild/users/user_3AniccObAoDJgCkSlT6RJk7a8NL/uploaded-1782951920221-rb0wtby4.jpg"},{"imageSrc":"https://storage.googleapis.com/webild/users/user_3AniccObAoDJgCkSlT6RJk7a8NL/uploaded-1782952546030-f2ubckey.jpg"},{"imageSrc":"https://storage.googleapis.com/webild/users/user_3AniccObAoDJgCkSlT6RJk7a8NL/uploaded-1782951363731-ti1gwsue.jpg"},{"imageSrc":"https://images.unsplash.com/photo-1530915534664-4ac6423816b7?q=80&w=1000&auto=format&fit=crop"},{"imageSrc":"https://images.unsplash.com/photo-1554068865-24cecd4e34b8?q=80&w=1000&auto=format&fit=crop"},{"imageSrc":"https://storage.googleapis.com/webild/users/user_3AniccObAoDJgCkSlT6RJk7a8NL/uploaded-1782951363730-qzocx6gy.webp"},{"imageSrc":"https://images.unsplash.com/photo-1542144582-1ba00456b5e3?q=80&w=1000&auto=format&fit=crop"},{"imageSrc":"https://images.unsplash.com/photo-1560012057-4372e14c5085?q=80&w=1000&auto=format&fit=crop"}]}
        primaryButton={{"href":"#facilities","text":"View Facilities"}}
        secondaryButton={{"href":"#contact","text":"Contact Us"}}
      />
            </div>
  );
}
