// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactBar from "@/components/sections/contact/ContactBar";
import { Phone, MessageCircle, Mail } from "lucide-react";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
              <ContactBar
                textAnimation="fade-blur"
                tag="Get in Touch"
                title={"Speak with one\nof our experts"}
                options={[
                  { icon: MessageCircle, label: "Whatsapp", href: "https://wa.me/1234567890" },
                  { icon: Mail, label: "Email", href: "mailto:hello@joescoffee.com" },
                  { icon: Phone, label: "Number", href: "tel:+1234567890" },
                ]}
              />
            </div>
  );
}
