// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features" section.

import React from 'react';
import FeaturesGridSplitLarge from "@/components/sections/features/FeaturesGridSplitLarge";

export default function FeaturesSection(): React.JSX.Element {
  return (
    <div id="features" data-section="features">
              <FeaturesGridSplitLarge
        textAnimation="fade-blur"
        tag="Events & Tournaments"
        title="Get Involved in the Community"
        description="From casual social mixers to competitive club championships, there's always something happening at the club."
        topItems={[{"imageSrc":"https://images.unsplash.com/photo-1530915534664-4ac6423816b7?q=80&w=1000&auto=format&fit=crop","description":"Compete in our annual club championships across various age groups and skill levels. A great way to challenge yourself and meet other members.","title":"Annual Championships"},{"imageSrc":"https://images.unsplash.com/photo-1554068865-24cecd4e34b8?q=80&w=1000&auto=format&fit=crop","description":"Join us for our monthly social mixers. Enjoy casual round-robin play followed by drinks and appetizers in the clubhouse.","title":"Social Mixers"}]}
        bottomItem={{"primaryButton":{"text":"Join a League","href":"#leagues"},"imageSrc":"https://storage.googleapis.com/webild/users/user_3AniccObAoDJgCkSlT6RJk7a8NL/uploaded-1782951363731-ti1gwsue.jpg","description":"Join our competitive leagues and test your skills against players of similar levels. We offer singles, doubles, and mixed leagues year-round.","title":"Club Leagues"}}
      />
            </div>
  );
}
