// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroBillboardBrandFloatingCards from "@/components/sections/hero/HeroBillboardBrandFloatingCards";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
              <HeroBillboardBrandFloatingCards
        textAnimation="fade-blur"
        brand="Grand Slam Club"
        description="Experience world-class tennis facilities, professional coaching, and a vibrant community. Whether you're a beginner or a seasoned pro, our courts are ready for you."
        primaryButton={{"href":"#book","text":"Book a Court"}}
        secondaryButton={{"text":"Join the Club","href":"#membership"}}
        videoSrc="https://storage.googleapis.com/webild/default/templates/tennis/hero.mp4"
        floatingCards={[{"name":"Clay Courts","imageSrc":"https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?q=80&w=1000&auto=format&fit=crop"},{"name":"Grass Courts","imageSrc":"https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?q=80&w=1000&auto=format&fit=crop"}]}
      />
            </div>
  );
}
