// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "menu" section.

import React from 'react';
import FeaturesFilterGrid from "@/components/sections/features/FeaturesFilterGrid";

export default function MenuSection(): React.JSX.Element {
  return (
    <div id="menu" data-section="menu">
              <FeaturesFilterGrid
        textAnimation="fade-blur"
        tag="Our Facilities"
        title="Everything You Need to Play Your Best"
        description="Discover our premium facilities designed for players of all levels."
        categories={["Courts","Coaching","Amenities"]}
        items={[{"category":"Courts","name":"Clay Courts","imageSrc":"https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?q=80&w=1000&auto=format&fit=crop"},{"imageSrc":"https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?q=80&w=1000&auto=format&fit=crop","category":"Courts","name":"Grass Courts"},{"imageSrc":"https://images.unsplash.com/photo-1589806053641-6101469b1110?q=80&w=1000&auto=format&fit=crop","category":"Courts","name":"Hard Courts"},{"category":"Courts","name":"Indoor Courts","imageSrc":"https://images.unsplash.com/photo-1530915534664-4ac6423816b7?q=80&w=1000&auto=format&fit=crop"},{"category":"Coaching","name":"Private Lessons","imageSrc":"https://images.unsplash.com/photo-1554068865-24cecd4e34b8?q=80&w=1000&auto=format&fit=crop"},{"category":"Coaching","name":"Group Clinics","imageSrc":"https://storage.googleapis.com/webild/users/user_3AniccObAoDJgCkSlT6RJk7a8NL/uploaded-1782951363730-qzocx6gy.webp"},{"category":"Coaching","name":"Junior Academy","imageSrc":"https://images.unsplash.com/photo-1542144582-1ba00456b5e3?q=80&w=1000&auto=format&fit=crop"},{"category":"Amenities","name":"Pro Shop","imageSrc":"https://images.unsplash.com/photo-1560012057-4372e14c5085?q=80&w=1000&auto=format&fit=crop"},{"category":"Amenities","name":"Clubhouse","imageSrc":"https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?q=80&w=1000&auto=format&fit=crop"},{"category":"Amenities","name":"Locker Rooms","imageSrc":"https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?q=80&w=1000&auto=format&fit=crop"}]}
      />
            </div>
  );
}
